version: '3.7'
services:
  web:
    image: nginx:alpine
    working_dir: /usr/share/nginx/html
    volumes:
      - .:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
  php:
    build: .
    volumes:
      - .:/usr/share/nginx/html
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
  db:
    image: postgres:11-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: gclubproject
      POSTGRES_DB: gclubproject
      POSTGRES_PASSWORD: qwerty
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
volumes:
  dbdata:
